In [2]:
print("Hello world")

Hello world


<h2>Creating numpy/n-d arrays</h2>

In [7]:
import numpy as np

<h6>Using np.array()</h6>

In [9]:
arr1 = np.array([1,2,3,4,5]) # using array()
arr1

array([1, 2, 3, 4, 5])

In [8]:
print(arr1)

[1 2 3 4 5]


In [10]:
type(arr1)

numpy.ndarray

In [20]:
# 2-d array
arr2 = np.array([[1,2,3],[4,5,6]])
arr2

array([[1, 2, 3],
       [4, 5, 6]])

<h6>Using np.zeros()</h6>

In [22]:
arr3 = np.zeros((2,3)) 

In [24]:
arr3

array([[0., 0., 0.],
       [0., 0., 0.]])

In [26]:
print(arr3)

[[0. 0. 0.]
 [0. 0. 0.]]


<h6>Using np.ones()</h6>

In [28]:
arr4 = np.ones((3,3))
arr4

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

<h6>Using np.identity()</h6>

In [32]:
arr5 = np.identity((5))

In [34]:
arr5

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

<h6>Using np.arange()</h6>

In [36]:
arr6 = np.arange(12)

In [38]:
arr6

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [40]:
arr6_1 = np.arange(4,12)
arr6_1

array([ 4,  5,  6,  7,  8,  9, 10, 11])

In [42]:
arr6_2 = np.arange(4,12,2)
arr6_2

array([ 4,  6,  8, 10])

<h6>Using np.linspace()</h6>

In [46]:
arr7 = np.linspace(2,20,2)
arr7

array([ 2., 20.])

<h2>Important Attribute</h2>

<h6>shape</h6>

In [51]:
arr1.shape

(5,)

In [53]:
arr2.shape

(5, 5)

In [59]:
arr8 = np.array([[1,2,3],[4,5,6]])
arr8

array([[1, 2, 3],
       [4, 5, 6]])

In [78]:
arr8.shape #structure or (rows,columns) of an array

(2, 3)

<h6>ndim</h6>

In [64]:
arr2.ndim

2

In [76]:
arr1.ndim #dimension of the array


1

<h6>size</h6>

In [74]:
arr2.size # no.of elements

25

<h6>itemsize</h6>

In [84]:
arr1.itemsize #size of each element

4

In [82]:
arr4.itemsize

8

<h6>dtype</h6>

In [88]:
arr4.dtype

dtype('float64')

In [90]:
arr1.dtype

dtype('int32')

<h6>astype</h6>

In [94]:
arr1.astype('float')

array([1., 2., 3., 4., 5.])

In [96]:
arr5.astype('int')

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

<h2>Python list v/s Numpy array</h2>

In [99]:
import sys

In [101]:
alist = range(100) # python list

In [103]:
arr = np.arange(100) # Numpy array

In [107]:
print(sys.getsizeof(2)*len(alist))

2800


In [113]:
print(arr.itemsize*arr.size)

400


In [115]:
import time

In [123]:
x = range(100000)
y = range(100000,200000)

start_time = time.time()

c=[(x,y) for x,y in zip(x,y)]
print(time.time() - start_time)

0.021999835968017578


In [7]:
arr9 = np.arange(24)
arr9

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [23]:
arr9 = np.arange(24) #we can change the shape of array using reshape()
arr9

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

<h2>Indexing, Slicing, Iteration</h2>

<h6>Indexing</h6>

In [15]:
arr1[2] #Indexing

3

<h6>Slicing</h6>

In [19]:
#SLicing

#arr[start:end:step]

In [17]:
arr1[2:4] #slicing from index 2 to 3

array([3, 4])

In [27]:
arr9[2:20:2] #From index 2 to 18 every second element

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [31]:
arr10 = np.arange(12).reshape(4,3)
arr10

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [43]:
arr10[0:4:2]

array([[0, 1, 2],
       [6, 7, 8]])

<h6>Iteration</h6>

In [45]:
arr10[1,2]

5

In [47]:
for i in arr10:
    print(i)

[0 1 2]
[3 4 5]
[6 7 8]
[ 9 10 11]


In [49]:
for i in np.nditer(arr10):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11


<h2>Numpy Operations</h2>

In [53]:
arr1 = np.array([1,2,3,4,5,6])
arr2 = np.array([4,5,6,7,8,9])

In [55]:
arr1-arr2

array([-3, -3, -3, -3, -3, -3])

In [57]:
arr1*2

array([ 2,  4,  6,  8, 10, 12])

In [59]:
arr1>3

array([False, False, False,  True,  True,  True])

In [65]:
arr3 = np.arange(6).reshape(2,3)
arr4 = np.arange(6,12).reshape(3,2)
arr3


array([[0, 1, 2],
       [3, 4, 5]])

In [63]:
arr4

array([[ 6,  7],
       [ 8,  9],
       [10, 11]])

<h6>Dot product</h6>

In [67]:
arr3.dot(arr4)

array([[ 28,  31],
       [100, 112]])

<h6>max() and min()</h6>

In [69]:
arr4.max()

11

In [71]:
arr4.min()

6

In [73]:
arr4.min(axis=0) #For column wise

array([6, 7])

In [77]:
arr4.min(axis=1) #Row wise

array([ 6,  8, 10])

<h6>sum()</h6>

In [79]:
arr4.sum()

51

In [81]:
arr4.sum(axis=0)

array([24, 27])

In [83]:
arr4.sum(axis=1)

array([13, 17, 21])

<h6>mean()</h6>

In [85]:
arr4.mean()

8.5

In [87]:
arr4.std()

1.707825127659933

In [89]:
np.sin(arr4)

array([[-0.2794155 ,  0.6569866 ],
       [ 0.98935825,  0.41211849],
       [-0.54402111, -0.99999021]])

<h2>Reshaping Numpy Arrays</h2>

In [92]:
arr4.ndim

2

<h6>Using ravel</h6>

In [94]:
arr4.ravel

<function ndarray.ravel>

In [98]:
arr4.ravel() #it converts nd to 1d

array([ 6,  7,  8,  9, 10, 11])

<h6>Using transpose()</h6>

In [100]:
arr4.transpose()

array([[ 6,  8, 10],
       [ 7,  9, 11]])

In [102]:
arr5 = np.arange(12,18).reshape(2,3)

In [123]:
arr4 = arr4.reshape(2,3)

In [127]:
arr5

array([[12, 13, 14],
       [15, 16, 17]])

<h6>using stacking</h6>

In [133]:
np.hstack((arr4,arr5)) #Combining two arrays horizontally

array([[ 6,  7,  8, 12, 13, 14],
       [ 9, 10, 11, 15, 16, 17]])

In [137]:
np.vstack((arr4,arr5)) #combining two arrays vertically

array([[ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

<h6>Using splitting|</h6>

In [ ]:
8374383649

In [141]:
np.vsplit(arr5,2) 

[array([[12, 13, 14]]), array([[15, 16, 17]])]

In [143]:
np.hsplit(arr5,3)

[array([[12],
        [15]]),
 array([[13],
        [16]]),
 array([[14],
        [17]])]

In [161]:
str = "In An Agreement"
print(str[1])

n


In [163]:
#str1 = ["he","is","good","boy","but","bad"]
str1 = str.split()
str2 = str1.copy()
start = str1[0].lower()

for i in str2:
    #print(i.lower())
    if i.lower() < start:
        start = i
print(start)
str1.sort()
print(str1)

An
['Agreement', 'An', 'In']


In [159]:
def first_dictionary_word(sentence):
    words = sentence.split()  
    mini =  min(words, key=lambda x: x.lower())
    maxi = max(words, key=lambda x: x.lower())

    return {mini,maxi}
print(first_dictionary_word("In An Agreement"))   
print(first_dictionary_word("He is bit slow")) 



{'In', 'Agreement'}
{'slow', 'bit'}
